### ISSUE TITLE
Installation error 

### ISSUE THREAD

**Issue by KyoHiki** [DataSciBurgoon/aopxplorer2#1]
When I tried to install aopxplorer2, the installation failed.
I obtained the following error messages.

> library(devtools)
> install_github("DataSciBurgoon/aopxplorer2")
Downloading GitHub repo DataSciBurgoon/aopxplorer2@master
from URL https://api.github.com/repos/DataSciBurgoon/aopxplorer2/zipball/master
Installing aopxplorer
"C:/PROGRA~1/R/R-34~1.4/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD build  \
  "C:\Users\XXXXXXX\AppData\Local\Temp\RtmpcVj7Hm\devtoolse00279f1d9e\DataSciBurgoon-aopxplorer2-93ef049"  \
  --no-resave-data --no-manual 
> 
> * checking for file 'C:\Users\XXXXXXX\AppData\Local\Temp\RtmpcVj7Hm\devtoolse00279f1d9e\DataSciBurgoon-aopxplorer2-93ef049/DESCRIPTION' ... OK
> * preparing 'aopxplorer':
> * checking DESCRIPTION meta-information ... OK
> * installing the package to build vignettes
>  警告:   命令 '"C:/PROGRA~1/R/R-34~1.4/bin/x64/Rcmd.exe" INSTALL -l "C:\Users\XXXXXXX\AppData\Local\Temp\RtmpQjF5Wy\Rinst1b4c1faf224e" --no-multiarch "C:/Users/XXXXXXX/AppData/Local/Temp/RtmpQjF5Wy/Rbuild1b4c1a2a74b9/aopxplorer"' の実行は状態 1 を持ちました 
>       -----------------------------------
> * installing *source* package 'aopxplorer' ...
> ** R
> Error in .install_package_code_files(".", instdir) : 
>  'C:/Users/XXXXXXX/AppData/Local/Temp/RtmpQjF5Wy/Rbuild1b4c1a2a74b9/aopxplorer/R' 中のファイルが 'Collate' 欄から欠損しています: 
>   sandbox.R
> ERROR: unable to collate and parse R files for package 'aopxplorer'
> * removing 'C:/Users/XXXXXXX/AppData/Local/Temp/RtmpQjF5Wy/Rinst1b4c1faf224e/aopxplorer'
> In R CMD INSTALL
>       -----------------------------------
> ERROR: package installation failed
> Installation failed: Command failed (1)

In contrast, the installation of "aopxplorer" (not aopxplorer2) was successfully completed.
I'd be glad if you could help me. Thanks.

Session Info is the followings.

> > sessionInfo()
> R version 3.4.4 (2018-03-15)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 7 x64 (build 7601) Service Pack 1
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=Japanese_Japan.932  LC_CTYPE=Japanese_Japan.932    LC_MONETARY=Japanese_Japan.932
> [4] LC_NUMERIC=C                   LC_TIME=Japanese_Japan.932    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] aopxplorer_0.1.1 shiny_1.1.0      jsonlite_1.5     devtools_1.13.6 
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_0.12.17      rstudioapi_0.7    knitr_1.20        magrittr_1.5      xtable_1.8-2     
>  [6] R6_2.2.2          rlang_0.2.1       httr_1.3.1        tools_3.4.4       data.table_1.11.4
> [11] git2r_0.21.0      withr_2.1.2       htmltools_0.3.6   yaml_2.1.19       digest_0.6.15    
> [16] crayon_1.3.4      later_0.7.3       htmlwidgets_1.2   promises_1.0.1    curl_3.2         
> [21] memoise_1.1.0     mime_0.5          compiler_3.4.4    httpuv_1.4.4.2    foreign_0.8-69

**Comment by DataSciBurgoon** [comment]
We migrated AOPXplorer over to the Cytoscape App Store: http://apps.cytoscape.org/apps/aopxplorer

This code is left here mostly for legacy reasons, and hadn't been completed yet. I'm sorry for the inconvenience, and I'll make a note on the README page.
